### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [trigg/DiscordOverlayLinux#29] opened 2020-05-11 12:00 UTC
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Discord Overlay for Linux on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by midget3111** [comment] 2020-05-11 14:15
Hey, I'm currently looking into the best way to package up and deploy the project. However, before we get to that point we need to implement a proper versioning system and have a stable release :).

**Comment by lineber** [comment] 2020-05-25 01:31
Is it possible to install it within the Steam Flatpak? Right now, the Discord Flatpak doesn't recognize the Steam games.

flatpak run --command=bash com.valvesoftware.Steam

**Comment by trigg** [comment] 2020-05-28 14:34
Duplicate of #16

**Closed as completed** 2020-05-28 15:07 UTC
Labels: duplicate
