### ISSUE TITLE
Doesn't run in i3wm

### ISSUE THREAD

**Issue by tuxiqae** [trigg/DiscordOverlayLinux#41] opened 2020-07-04 10:53 UTC
Tried to run the executable at `~/.local/bin/discord-overlay` after installing, got the following error.
I am using i3wm, not sure if tiling WMs are meant to be supported.

Thanks!

```python
[USER@host:~]$> python3 ~/.local/bin/discord-overlay
Traceback (most recent call last):
  File "/home/USER/.local/bin/discord-overlay", line 33, in <module>
    sys.exit(load_entry_point('discordoverlaylinux==0.0.1', 'console_scripts', 'discord-overlay')())
  File "/home/USER/.local/bin/discord-overlay", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/USER/.local/lib/python3.8/site-packages/discord_overlay/__init__.py", line 1, in <module>
    from .discord_overlay import *
  File "/home/USER/.local/lib/python3.8/site-packages/discord_overlay/discord_overlay.py", line 21, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: /home/USER/.local/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5
```

**Comment by xenorio** [comment] 2020-07-16 11:28
cannot reproduce on Pop!_OS 20.04 with i3 4.17.1 and X11

everything works great for me

**Comment by trigg** [comment] 2020-07-16 14:35
'undefined symbol' means that QT webengine is missing, fix for this depends on OS and/or package manager available. Apologies on late reply!

**Comment by Firobe** [comment] 2020-07-18 02:43
I can reproduce this exact same issue on Arch Linux/i3 with : 
- Python 3.8.3
- qt5-webengine 5.15.0
- PyQtWebEngine 5.15.0

The undefined symbol in question is `std::out_of_range::out_of_range` when unmangled. It's both present in the pip libQt5WebEngineCore.so.5 and the system one but undefined in both.

**Comment by Firobe** [comment] 2020-07-18 02:48
For now I fixed it by removing PyQtWebEngine with pip and instead installing the `python-pyqtwebengine` package from Pacman.

**Closed as completed** 2020-08-05 17:06 UTC
